title: "elianriezadotdev | A bored engineer's personal website"
author:
  name: Elian (Eli) Rieza
  email: elianrieza [at] ieee.org

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  A place to ramble about my electrical engineering classes, personal hardware projects and research notes.

# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/).
# If you want to use the latest Minima version on GitHub Pages, use the following setting and
# add a line comment on "theme: minima" above.
#remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  skin: classic

  # If you want to link only specific pages in the site-navigation, use this and list
  # the `path` property (as represented via Liquid) of the pages in the order they should
  # be rendered.
  nav_pages:
    - about.md

  # Set to `true` to show excerpts on the homepage.
  #show_excerpts: false

  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023)
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  # Social Media Links
  # Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #
  # Entry keys:
  # * title    Tooltip rendered on hovering over icon.
  # * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  # * url      Full URL of social profile.
  social_links:
    - title: Elian's GitHub
      icon: github
      url: "https://github.com/nail-e"
    - title: Elian's LinkedIn
      icon: linkedin
      url: "https://linkedin.com/elian-r"
    - title: elianrieza.dev RSS
      icon: rss
      url: "http://elianrieza.dev/feed.xml"
